/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject2;

/**
 *
 * @author yannivtroadec
 */
public class Atelier_Fabrication_restreint extends javax.swing.JFrame {

    /**
     * Creates new form Atelier_Fabrication_restreint
     */
    public Atelier_Fabrication_restreint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuProduit = new javax.swing.JMenu();
        MenuItemAfficherProduit = new javax.swing.JMenuItem();
        MenuMachine = new javax.swing.JMenu();
        MenuItemAfficherMachine = new javax.swing.JMenuItem();
        MenuFiabilite = new javax.swing.JMenu();
        MenuItemSignalerEvenement = new javax.swing.JMenuItem();
        MenuItemAfficherEvenements = new javax.swing.JMenuItem();
        MenuPoste = new javax.swing.JMenu();
        MenuItemAfficherPoste = new javax.swing.JMenuItem();
        MenuOperation = new javax.swing.JMenu();
        MenuItemAfficherOperation = new javax.swing.JMenuItem();
        MenuGamme = new javax.swing.JMenu();
        MenuItemAfficherGamme = new javax.swing.JMenuItem();
        MenuStocks = new javax.swing.JMenu();
        MenuStockBrut = new javax.swing.JMenu();
        MenuItemStockBrutAfficher = new javax.swing.JMenuItem();
        MenuStockProduitsFinis = new javax.swing.JMenu();
        MenuItemStockProduitsFinisAfficher = new javax.swing.JMenuItem();
        MenuPlan = new javax.swing.JMenu();
        MenuItemPlan = new javax.swing.JMenuItem();
        MenuItemLegendeDuPlan = new javax.swing.JMenuItem();
        MenuDeconnexion = new javax.swing.JMenu();
        MenuSeDeconnecter = new javax.swing.JMenu();
        MenuItemSeDeconnecterNON = new javax.swing.JMenuItem();
        MenuItemSeDeconnecterOUI = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atelier de Fabrication");

        jLabel1.setText("Etat: Connecté(e)");

        jLabel2.setText("Statut: Opérateur");

        jLabel3.setText("Thelier, Troadec et Vermeerbergen Ferry");

        jLabel4.setText("Atelier de Fabrication");

        jLabel5.setText("Projet S2");

        jLabel6.setText("STH1");

        jLabel7.setText("B8");

        MenuProduit.setText("Produit");

        MenuItemAfficherProduit.setText("Afficher");
        MenuItemAfficherProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAfficherProduitActionPerformed(evt);
            }
        });
        MenuProduit.add(MenuItemAfficherProduit);

        jMenuBar1.add(MenuProduit);

        MenuMachine.setText("Machine");

        MenuItemAfficherMachine.setText("Afficher");
        MenuItemAfficherMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAfficherMachineActionPerformed(evt);
            }
        });
        MenuMachine.add(MenuItemAfficherMachine);

        MenuFiabilite.setText("Fiabilité");

        MenuItemSignalerEvenement.setText("Signaler un évènement");
        MenuItemSignalerEvenement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSignalerEvenementActionPerformed(evt);
            }
        });
        MenuFiabilite.add(MenuItemSignalerEvenement);

        MenuItemAfficherEvenements.setText("Afficher les évènements");
        MenuItemAfficherEvenements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAfficherEvenementsActionPerformed(evt);
            }
        });
        MenuFiabilite.add(MenuItemAfficherEvenements);

        MenuMachine.add(MenuFiabilite);

        jMenuBar1.add(MenuMachine);

        MenuPoste.setText("Poste");

        MenuItemAfficherPoste.setText("Afficher");
        MenuItemAfficherPoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAfficherPosteActionPerformed(evt);
            }
        });
        MenuPoste.add(MenuItemAfficherPoste);

        jMenuBar1.add(MenuPoste);

        MenuOperation.setText("Opération");

        MenuItemAfficherOperation.setText("Afficher");
        MenuItemAfficherOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAfficherOperationActionPerformed(evt);
            }
        });
        MenuOperation.add(MenuItemAfficherOperation);

        jMenuBar1.add(MenuOperation);

        MenuGamme.setText("Gamme");

        MenuItemAfficherGamme.setText("Afficher");
        MenuItemAfficherGamme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAfficherGammeActionPerformed(evt);
            }
        });
        MenuGamme.add(MenuItemAfficherGamme);

        jMenuBar1.add(MenuGamme);

        MenuStocks.setText("Stocks");

        MenuStockBrut.setText("StockBrut");

        MenuItemStockBrutAfficher.setText("Afficher");
        MenuItemStockBrutAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemStockBrutAfficherActionPerformed(evt);
            }
        });
        MenuStockBrut.add(MenuItemStockBrutAfficher);

        MenuStocks.add(MenuStockBrut);

        MenuStockProduitsFinis.setText("Stock Produits Finis");

        MenuItemStockProduitsFinisAfficher.setText("Afficher");
        MenuItemStockProduitsFinisAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemStockProduitsFinisAfficherActionPerformed(evt);
            }
        });
        MenuStockProduitsFinis.add(MenuItemStockProduitsFinisAfficher);

        MenuStocks.add(MenuStockProduitsFinis);

        jMenuBar1.add(MenuStocks);

        MenuPlan.setText("Plan");

        MenuItemPlan.setText("Afficher le Plan");
        MenuItemPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPlanActionPerformed(evt);
            }
        });
        MenuPlan.add(MenuItemPlan);

        MenuItemLegendeDuPlan.setText("Légende Plan");
        MenuItemLegendeDuPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLegendeDuPlanActionPerformed(evt);
            }
        });
        MenuPlan.add(MenuItemLegendeDuPlan);

        jMenuBar1.add(MenuPlan);

        MenuDeconnexion.setText("Deconnexion");

        MenuSeDeconnecter.setText("Se deconnecter");

        MenuItemSeDeconnecterNON.setText("Non");
        MenuItemSeDeconnecterNON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSeDeconnecterNONActionPerformed(evt);
            }
        });
        MenuSeDeconnecter.add(MenuItemSeDeconnecterNON);

        MenuItemSeDeconnecterOUI.setText("Oui");
        MenuItemSeDeconnecterOUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSeDeconnecterOUIActionPerformed(evt);
            }
        });
        MenuSeDeconnecter.add(MenuItemSeDeconnecterOUI);

        MenuDeconnexion.add(MenuSeDeconnecter);

        jMenuBar1.add(MenuDeconnexion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 544, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemAfficherProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAfficherProduitActionPerformed
        // TODO add your handling code here:
        AffichageDesProduits f = new AffichageDesProduits();
        f.setVisible(true);

    }//GEN-LAST:event_MenuItemAfficherProduitActionPerformed

    private void MenuItemSeDeconnecterOUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSeDeconnecterOUIActionPerformed
        // TODO add your handling code here:
        Accueil f = new Accueil();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemSeDeconnecterOUIActionPerformed

    private void MenuItemSeDeconnecterNONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSeDeconnecterNONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemSeDeconnecterNONActionPerformed

    private void MenuItemAfficherMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAfficherMachineActionPerformed
        // TODO add your handling code here:
        AffichageDesMachines f = new AffichageDesMachines();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemAfficherMachineActionPerformed

    private void MenuItemAfficherPosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAfficherPosteActionPerformed
        // TODO add your handling code here:
        AffichageDesPostes f = new AffichageDesPostes();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemAfficherPosteActionPerformed

    private void MenuItemAfficherOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAfficherOperationActionPerformed
        // TODO add your handling code here:
        AffichageDesOperations f = new AffichageDesOperations();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemAfficherOperationActionPerformed

    private void MenuItemAfficherGammeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAfficherGammeActionPerformed
        // TODO add your handling code here:
        AffichageDesGammes f = new AffichageDesGammes();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemAfficherGammeActionPerformed

    private void MenuItemStockBrutAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemStockBrutAfficherActionPerformed
        // TODO add your handling code here:
        AffichageDesStockBruts f = new AffichageDesStockBruts();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemStockBrutAfficherActionPerformed

    private void MenuItemStockProduitsFinisAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemStockProduitsFinisAfficherActionPerformed
        // TODO add your handling code here:
        AffichagesDesStockProduitsFinis f = new AffichagesDesStockProduitsFinis();
         f.setVisible(true);
    }//GEN-LAST:event_MenuItemStockProduitsFinisAfficherActionPerformed

    private void MenuItemPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPlanActionPerformed
        // TODO add your handling code here:
        MaFenetre fen = new MaFenetre();
        fen.setVisible(true);
    }//GEN-LAST:event_MenuItemPlanActionPerformed

    private void MenuItemLegendeDuPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLegendeDuPlanActionPerformed
        // TODO add your handling code here:
        MaFenetre2 f = new MaFenetre2();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemLegendeDuPlanActionPerformed

    private void MenuItemSignalerEvenementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSignalerEvenementActionPerformed
        // TODO add your handling code here:
        IG_Fiabilite f = new IG_Fiabilite();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemSignalerEvenementActionPerformed

    private void MenuItemAfficherEvenementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAfficherEvenementsActionPerformed
        // TODO add your handling code here:
        AffichageDesEvents f = new AffichageDesEvents();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemAfficherEvenementsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Atelier_Fabrication_restreint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Atelier_Fabrication_restreint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Atelier_Fabrication_restreint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Atelier_Fabrication_restreint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Atelier_Fabrication_restreint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuDeconnexion;
    private javax.swing.JMenu MenuFiabilite;
    private javax.swing.JMenu MenuGamme;
    private javax.swing.JMenuItem MenuItemAfficherEvenements;
    private javax.swing.JMenuItem MenuItemAfficherGamme;
    private javax.swing.JMenuItem MenuItemAfficherMachine;
    private javax.swing.JMenuItem MenuItemAfficherOperation;
    private javax.swing.JMenuItem MenuItemAfficherPoste;
    private javax.swing.JMenuItem MenuItemAfficherProduit;
    private javax.swing.JMenuItem MenuItemLegendeDuPlan;
    private javax.swing.JMenuItem MenuItemPlan;
    private javax.swing.JMenuItem MenuItemSeDeconnecterNON;
    private javax.swing.JMenuItem MenuItemSeDeconnecterOUI;
    private javax.swing.JMenuItem MenuItemSignalerEvenement;
    private javax.swing.JMenuItem MenuItemStockBrutAfficher;
    private javax.swing.JMenuItem MenuItemStockProduitsFinisAfficher;
    private javax.swing.JMenu MenuMachine;
    private javax.swing.JMenu MenuOperation;
    private javax.swing.JMenu MenuPlan;
    private javax.swing.JMenu MenuPoste;
    private javax.swing.JMenu MenuProduit;
    private javax.swing.JMenu MenuSeDeconnecter;
    private javax.swing.JMenu MenuStockBrut;
    private javax.swing.JMenu MenuStockProduitsFinis;
    private javax.swing.JMenu MenuStocks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
