/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject2;

/**
 *
 * @author yannivtroadec
 */
public class Atelier_Fabrication extends javax.swing.JFrame {

    
    /**
     * Creates new form Atelier_Fabrication
     */
    public static String dir = "/Users/yannivtroadec/Desktop/données info";
    public static String dir2 = "/Users/yannivtroadec/Desktop/passwords info";

    public Atelier_Fabrication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jColorChooser1 = new javax.swing.JColorChooser();
        jMenuItem14 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuProduit = new javax.swing.JMenu();
        MenuItemCreerProduit = new javax.swing.JMenuItem();
        MenuItemModifierProduit = new javax.swing.JMenuItem();
        MenuItemSupprimerProduit = new javax.swing.JMenuItem();
        MenuItemAfficherProduit = new javax.swing.JMenuItem();
        MenuMachine = new javax.swing.JMenu();
        MenuItemCreerMachine = new javax.swing.JMenuItem();
        MenuItemModifierMachine = new javax.swing.JMenuItem();
        MenuItemSupprimerMachine = new javax.swing.JMenuItem();
        MenuItemAfficherMachine = new javax.swing.JMenuItem();
        MenuFiabilite = new javax.swing.JMenu();
        MenuItemSignalerEvenement = new javax.swing.JMenuItem();
        MenuItemAfficherEvenements = new javax.swing.JMenuItem();
        MenuItemCalculerFiabilite = new javax.swing.JMenuItem();
        MenuItemAfficherFiabilité = new javax.swing.JMenuItem();
        MenuPoste = new javax.swing.JMenu();
        MenuItemCreerPoste = new javax.swing.JMenuItem();
        MenuItemModifierPoste = new javax.swing.JMenuItem();
        MenuItemSupprimerPoste = new javax.swing.JMenuItem();
        MenuItemAfficherPoste = new javax.swing.JMenuItem();
        MenuOperation = new javax.swing.JMenu();
        MenuItemCreerOperation = new javax.swing.JMenuItem();
        MenuItemModifierOperation = new javax.swing.JMenuItem();
        MenuItemSupprimerOperation = new javax.swing.JMenuItem();
        MenuItemAfficherOperation = new javax.swing.JMenuItem();
        MenuGamme = new javax.swing.JMenu();
        MenuItemCreerGamme = new javax.swing.JMenuItem();
        MenuItemModifierGamme = new javax.swing.JMenuItem();
        MenuItemSupprimerGamme = new javax.swing.JMenuItem();
        MenuItemAfficherGamme = new javax.swing.JMenuItem();
        MenuOperateur = new javax.swing.JMenu();
        MenuItemCreerOperateur = new javax.swing.JMenuItem();
        MenuItemModifierOperateur = new javax.swing.JMenuItem();
        MenuItemSupprimerOperateur = new javax.swing.JMenuItem();
        MenuItemAfficherOperateur = new javax.swing.JMenuItem();
        MenuStocks = new javax.swing.JMenu();
        MenuStockBrut = new javax.swing.JMenu();
        MenuItemStockBrutAjouter = new javax.swing.JMenuItem();
        MenuItemStockBrutModifier = new javax.swing.JMenuItem();
        MenuItemStockBrutSupprimer = new javax.swing.JMenuItem();
        MenuItemStockBrutAfficher = new javax.swing.JMenuItem();
        MenuStockProduitsFinis = new javax.swing.JMenu();
        MenuItemStockProduitsFinisAjouter = new javax.swing.JMenuItem();
        MenuItemStockProduitsFinisModifier = new javax.swing.JMenuItem();
        MenuItemStockProduitsFinisSupprimer = new javax.swing.JMenuItem();
        MenuItemStockProduitsFinisAfficher = new javax.swing.JMenuItem();
        MenuPlan = new javax.swing.JMenu();
        MenuItemPlanAfficher = new javax.swing.JMenuItem();
        MenuItemLegendeDuPlan = new javax.swing.JMenuItem();
        MenuCompte = new javax.swing.JMenu();
        MenuItemInformationsCompte = new javax.swing.JMenuItem();
        MenuItemParametresCompte = new javax.swing.JMenuItem();
        MenuDeconnexion = new javax.swing.JMenu();
        MenuSeDeconnecter = new javax.swing.JMenu();
        MenuItemSeDeconnecterOUI = new javax.swing.JMenuItem();
        MenuItemSeDeconnecterNON = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem15.setText("jMenuItem15");

        jMenuItem14.setText("jMenuItem14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atelier de Fabrication");

        jLabel1.setText("Thelier, Troadec et Vermeerbergen Ferry");

        jLabel2.setText("Atelier de Fabrication");

        jLabel3.setText("Projet S2");

        jLabel4.setText("STH1");

        jLabel5.setText("B8");

        jLabel6.setText("Etat: Connecté(e)");

        jLabel7.setText("Statut: Chef Atelier");

        MenuProduit.setText("Produit");

        MenuItemCreerProduit.setText("Créer");
        MenuItemCreerProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCreerProduitActionPerformed(evt);
            }
        });
        MenuProduit.add(MenuItemCreerProduit);

        MenuItemModifierProduit.setText("Modifier");
        MenuItemModifierProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemModifierProduitActionPerformed(evt);
            }
        });
        MenuProduit.add(MenuItemModifierProduit);

        MenuItemSupprimerProduit.setText("Supprimer");
        MenuItemSupprimerProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSupprimerProduitActionPerformed(evt);
            }
        });
        MenuProduit.add(MenuItemSupprimerProduit);

        MenuItemAfficherProduit.setText("Afficher");
        MenuItemAfficherProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAfficherProduitActionPerformed(evt);
            }
        });
        MenuProduit.add(MenuItemAfficherProduit);

        jMenuBar1.add(MenuProduit);

        MenuMachine.setText("Machine");

        MenuItemCreerMachine.setText("Créer");
        MenuItemCreerMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCreerMachineActionPerformed(evt);
            }
        });
        MenuMachine.add(MenuItemCreerMachine);

        MenuItemModifierMachine.setText("Modifier");
        MenuItemModifierMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemModifierMachineActionPerformed(evt);
            }
        });
        MenuMachine.add(MenuItemModifierMachine);

        MenuItemSupprimerMachine.setText("Supprimer");
        MenuItemSupprimerMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSupprimerMachineActionPerformed(evt);
            }
        });
        MenuMachine.add(MenuItemSupprimerMachine);

        MenuItemAfficherMachine.setText("Afficher");
        MenuItemAfficherMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAfficherMachineActionPerformed(evt);
            }
        });
        MenuMachine.add(MenuItemAfficherMachine);

        MenuFiabilite.setText("Fiabilité");

        MenuItemSignalerEvenement.setText("Signaler un évènement");
        MenuItemSignalerEvenement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSignalerEvenementActionPerformed(evt);
            }
        });
        MenuFiabilite.add(MenuItemSignalerEvenement);

        MenuItemAfficherEvenements.setText("Afficher les évènements");
        MenuItemAfficherEvenements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAfficherEvenementsActionPerformed(evt);
            }
        });
        MenuFiabilite.add(MenuItemAfficherEvenements);

        MenuItemCalculerFiabilite.setText("Calculer Fiabilité");
        MenuItemCalculerFiabilite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCalculerFiabiliteActionPerformed(evt);
            }
        });
        MenuFiabilite.add(MenuItemCalculerFiabilite);

        MenuItemAfficherFiabilité.setText("Afficher Fiabilité");
        MenuItemAfficherFiabilité.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAfficherFiabilitéActionPerformed(evt);
            }
        });
        MenuFiabilite.add(MenuItemAfficherFiabilité);

        MenuMachine.add(MenuFiabilite);

        jMenuBar1.add(MenuMachine);

        MenuPoste.setText("Poste");

        MenuItemCreerPoste.setText("Créer");
        MenuItemCreerPoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCreerPosteActionPerformed(evt);
            }
        });
        MenuPoste.add(MenuItemCreerPoste);

        MenuItemModifierPoste.setText("Modifier");
        MenuItemModifierPoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemModifierPosteActionPerformed(evt);
            }
        });
        MenuPoste.add(MenuItemModifierPoste);

        MenuItemSupprimerPoste.setText("Supprimer");
        MenuItemSupprimerPoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSupprimerPosteActionPerformed(evt);
            }
        });
        MenuPoste.add(MenuItemSupprimerPoste);

        MenuItemAfficherPoste.setText("Afficher");
        MenuItemAfficherPoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAfficherPosteActionPerformed(evt);
            }
        });
        MenuPoste.add(MenuItemAfficherPoste);

        jMenuBar1.add(MenuPoste);

        MenuOperation.setText("Opération");

        MenuItemCreerOperation.setText("Créer");
        MenuItemCreerOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCreerOperationActionPerformed(evt);
            }
        });
        MenuOperation.add(MenuItemCreerOperation);

        MenuItemModifierOperation.setText("Modifier");
        MenuItemModifierOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemModifierOperationActionPerformed(evt);
            }
        });
        MenuOperation.add(MenuItemModifierOperation);

        MenuItemSupprimerOperation.setText("Supprimer");
        MenuItemSupprimerOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSupprimerOperationActionPerformed(evt);
            }
        });
        MenuOperation.add(MenuItemSupprimerOperation);

        MenuItemAfficherOperation.setText("Afficher");
        MenuItemAfficherOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAfficherOperationActionPerformed(evt);
            }
        });
        MenuOperation.add(MenuItemAfficherOperation);

        jMenuBar1.add(MenuOperation);

        MenuGamme.setText("Gamme");

        MenuItemCreerGamme.setText("Créer");
        MenuItemCreerGamme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCreerGammeActionPerformed(evt);
            }
        });
        MenuGamme.add(MenuItemCreerGamme);

        MenuItemModifierGamme.setText("Modifier");
        MenuItemModifierGamme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemModifierGammeActionPerformed(evt);
            }
        });
        MenuGamme.add(MenuItemModifierGamme);

        MenuItemSupprimerGamme.setText("Supprimer");
        MenuItemSupprimerGamme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSupprimerGammeActionPerformed(evt);
            }
        });
        MenuGamme.add(MenuItemSupprimerGamme);

        MenuItemAfficherGamme.setText("Afficher");
        MenuItemAfficherGamme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAfficherGammeActionPerformed(evt);
            }
        });
        MenuGamme.add(MenuItemAfficherGamme);

        jMenuBar1.add(MenuGamme);

        MenuOperateur.setText("Opérateur");

        MenuItemCreerOperateur.setText("Créer");
        MenuItemCreerOperateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCreerOperateurActionPerformed(evt);
            }
        });
        MenuOperateur.add(MenuItemCreerOperateur);

        MenuItemModifierOperateur.setText("Modifier");
        MenuItemModifierOperateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemModifierOperateurActionPerformed(evt);
            }
        });
        MenuOperateur.add(MenuItemModifierOperateur);

        MenuItemSupprimerOperateur.setText("Supprimer");
        MenuItemSupprimerOperateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSupprimerOperateurActionPerformed(evt);
            }
        });
        MenuOperateur.add(MenuItemSupprimerOperateur);

        MenuItemAfficherOperateur.setText("Afficher");
        MenuItemAfficherOperateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAfficherOperateurActionPerformed(evt);
            }
        });
        MenuOperateur.add(MenuItemAfficherOperateur);

        jMenuBar1.add(MenuOperateur);

        MenuStocks.setText("Stocks");

        MenuStockBrut.setText("Stock Brut");

        MenuItemStockBrutAjouter.setText("Ajouter");
        MenuItemStockBrutAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemStockBrutAjouterActionPerformed(evt);
            }
        });
        MenuStockBrut.add(MenuItemStockBrutAjouter);

        MenuItemStockBrutModifier.setText("Modifier");
        MenuItemStockBrutModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemStockBrutModifierActionPerformed(evt);
            }
        });
        MenuStockBrut.add(MenuItemStockBrutModifier);

        MenuItemStockBrutSupprimer.setText("Supprimer");
        MenuItemStockBrutSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemStockBrutSupprimerActionPerformed(evt);
            }
        });
        MenuStockBrut.add(MenuItemStockBrutSupprimer);

        MenuItemStockBrutAfficher.setText("Afficher");
        MenuItemStockBrutAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemStockBrutAfficherActionPerformed(evt);
            }
        });
        MenuStockBrut.add(MenuItemStockBrutAfficher);

        MenuStocks.add(MenuStockBrut);

        MenuStockProduitsFinis.setText("Stock Produits Finis");

        MenuItemStockProduitsFinisAjouter.setText("Ajouter");
        MenuItemStockProduitsFinisAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemStockProduitsFinisAjouterActionPerformed(evt);
            }
        });
        MenuStockProduitsFinis.add(MenuItemStockProduitsFinisAjouter);

        MenuItemStockProduitsFinisModifier.setText("Modifier");
        MenuItemStockProduitsFinisModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemStockProduitsFinisModifierActionPerformed(evt);
            }
        });
        MenuStockProduitsFinis.add(MenuItemStockProduitsFinisModifier);

        MenuItemStockProduitsFinisSupprimer.setText("Supprimer");
        MenuItemStockProduitsFinisSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemStockProduitsFinisSupprimerActionPerformed(evt);
            }
        });
        MenuStockProduitsFinis.add(MenuItemStockProduitsFinisSupprimer);

        MenuItemStockProduitsFinisAfficher.setText("Afficher");
        MenuItemStockProduitsFinisAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemStockProduitsFinisAfficherActionPerformed(evt);
            }
        });
        MenuStockProduitsFinis.add(MenuItemStockProduitsFinisAfficher);

        MenuStocks.add(MenuStockProduitsFinis);

        jMenuBar1.add(MenuStocks);

        MenuPlan.setText("Plan");

        MenuItemPlanAfficher.setText("Afficher le Plan");
        MenuItemPlanAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPlanAfficherActionPerformed(evt);
            }
        });
        MenuPlan.add(MenuItemPlanAfficher);

        MenuItemLegendeDuPlan.setText("Légende Plan");
        MenuItemLegendeDuPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLegendeDuPlanActionPerformed(evt);
            }
        });
        MenuPlan.add(MenuItemLegendeDuPlan);

        jMenuBar1.add(MenuPlan);

        MenuCompte.setText("Compte");

        MenuItemInformationsCompte.setText("Informations");
        MenuItemInformationsCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemInformationsCompteActionPerformed(evt);
            }
        });
        MenuCompte.add(MenuItemInformationsCompte);

        MenuItemParametresCompte.setText("Paramètres");
        MenuItemParametresCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemParametresCompteActionPerformed(evt);
            }
        });
        MenuCompte.add(MenuItemParametresCompte);

        jMenuBar1.add(MenuCompte);

        MenuDeconnexion.setText("Déconnexion");

        MenuSeDeconnecter.setText("Se déconnecter");

        MenuItemSeDeconnecterOUI.setText("Oui");
        MenuItemSeDeconnecterOUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSeDeconnecterOUIActionPerformed(evt);
            }
        });
        MenuSeDeconnecter.add(MenuItemSeDeconnecterOUI);

        MenuItemSeDeconnecterNON.setText("Non");
        MenuItemSeDeconnecterNON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSeDeconnecterNONActionPerformed(evt);
            }
        });
        MenuSeDeconnecter.add(MenuItemSeDeconnecterNON);

        MenuDeconnexion.add(MenuSeDeconnecter);

        jMenuBar1.add(MenuDeconnexion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(488, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemCreerMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCreerMachineActionPerformed
        // TODO add your handling code here:
        IG_Machine fenetre1 = new IG_Machine();
        fenetre1.setVisible(true);
    }//GEN-LAST:event_MenuItemCreerMachineActionPerformed

    private void MenuItemCreerPosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCreerPosteActionPerformed
        // TODO add your handling code here:
        IG_Poste f = new IG_Poste();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemCreerPosteActionPerformed

    private void MenuItemCreerGammeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCreerGammeActionPerformed
        // TODO add your handling code here:
        IG_Gamme f = new IG_Gamme();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemCreerGammeActionPerformed

    private void MenuItemModifierMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemModifierMachineActionPerformed
        // TODO add your handling code here:
        ModifierMachine f = new ModifierMachine();
        f.setVisible(true);

    }//GEN-LAST:event_MenuItemModifierMachineActionPerformed

    private void MenuItemModifierGammeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemModifierGammeActionPerformed
        // TODO add your handling code here:
        ModifierGamme f = new ModifierGamme();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemModifierGammeActionPerformed

    private void MenuItemSupprimerMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSupprimerMachineActionPerformed
        // TODO add your handling code here:
        SupprimerMachine f = new SupprimerMachine();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemSupprimerMachineActionPerformed

    private void MenuItemAfficherMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAfficherMachineActionPerformed
        // TODO add your handling code here:
        AffichageDesMachines f = new AffichageDesMachines();
        f.setVisible(true);

    }//GEN-LAST:event_MenuItemAfficherMachineActionPerformed

    private void MenuItemAfficherPosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAfficherPosteActionPerformed
        // TODO add your handling code here:
        AffichageDesPostes f = new AffichageDesPostes();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemAfficherPosteActionPerformed

    private void MenuItemAfficherGammeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAfficherGammeActionPerformed
        // TODO add your handling code here:
        AffichageDesGammes f = new AffichageDesGammes();
        f.setVisible(true);

    }//GEN-LAST:event_MenuItemAfficherGammeActionPerformed

    private void MenuItemModifierPosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemModifierPosteActionPerformed
        // TODO add your handling code here:
        ModifierPoste f = new ModifierPoste();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemModifierPosteActionPerformed

    private void MenuItemSupprimerGammeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSupprimerGammeActionPerformed
        // TODO add your handling code here:
        SupprimerGamme f = new SupprimerGamme();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemSupprimerGammeActionPerformed

    private void MenuItemSupprimerPosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSupprimerPosteActionPerformed
        // TODO add your handling code here:
        SupprimerPoste f = new SupprimerPoste();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemSupprimerPosteActionPerformed

    private void MenuItemSeDeconnecterNONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSeDeconnecterNONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemSeDeconnecterNONActionPerformed

    private void MenuItemSeDeconnecterOUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSeDeconnecterOUIActionPerformed
        // TODO add your handling code here:
        Accueil f = new Accueil();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuItemSeDeconnecterOUIActionPerformed

    private void MenuItemInformationsCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemInformationsCompteActionPerformed
        // TODO add your handling code here:
        AffichageCompte f = new AffichageCompte();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemInformationsCompteActionPerformed

    private void MenuItemParametresCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemParametresCompteActionPerformed
        // TODO add your handling code here:
        ModifierCompte f = new ModifierCompte();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemParametresCompteActionPerformed

    private void MenuItemCreerProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCreerProduitActionPerformed
        // TODO add your handling code here:
        IG_Produit f = new IG_Produit();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemCreerProduitActionPerformed

    private void MenuItemSupprimerProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSupprimerProduitActionPerformed
        // TODO add your handling code here:
        SupprimerProduit f = new SupprimerProduit();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemSupprimerProduitActionPerformed

    private void MenuItemModifierProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemModifierProduitActionPerformed
        // TODO add your handling code here:
        ModifierProduit f = new ModifierProduit();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemModifierProduitActionPerformed

    private void MenuItemAfficherProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAfficherProduitActionPerformed
        // TODO add your handling code here:
        AffichageDesProduits f = new AffichageDesProduits();
        f.setVisible(true);

    }//GEN-LAST:event_MenuItemAfficherProduitActionPerformed

    private void MenuItemCreerOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCreerOperationActionPerformed
        // TODO add your handling code here:
        IG_Operation f = new IG_Operation();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemCreerOperationActionPerformed

    private void MenuItemModifierOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemModifierOperationActionPerformed
        // TODO add your handling code here:
        ModifierOperation f = new ModifierOperation();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemModifierOperationActionPerformed

    private void MenuItemSupprimerOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSupprimerOperationActionPerformed
        // TODO add your handling code here:
        SupprimerOperation f = new SupprimerOperation();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemSupprimerOperationActionPerformed

    private void MenuItemAfficherOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAfficherOperationActionPerformed
        // TODO add your handling code here:
        AffichageDesOperations f = new AffichageDesOperations();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemAfficherOperationActionPerformed

    private void MenuItemCreerOperateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCreerOperateurActionPerformed
        // TODO add your handling code here:
        IG_Operateur f = new IG_Operateur();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemCreerOperateurActionPerformed

    private void MenuItemModifierOperateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemModifierOperateurActionPerformed
        // TODO add your handling code here:
        ModifierOperateur f = new ModifierOperateur();
        f.setVisible(true);
        
    }//GEN-LAST:event_MenuItemModifierOperateurActionPerformed

    private void MenuItemSupprimerOperateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSupprimerOperateurActionPerformed
        // TODO add your handling code here:
        SupprimerOperateur f = new SupprimerOperateur();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemSupprimerOperateurActionPerformed

    private void MenuItemAfficherOperateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAfficherOperateurActionPerformed
        // TODO add your handling code here:
        AffichageDesOperateurs f = new AffichageDesOperateurs();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemAfficherOperateurActionPerformed

    private void MenuItemStockBrutAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemStockBrutAfficherActionPerformed
        // TODO add your handling code here:
        AffichageDesStockBruts f = new AffichageDesStockBruts();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemStockBrutAfficherActionPerformed

    private void MenuItemStockBrutModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemStockBrutModifierActionPerformed
        // TODO add your handling code here:
        ModifierStockBrut f = new ModifierStockBrut();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemStockBrutModifierActionPerformed

    private void MenuItemStockBrutAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemStockBrutAjouterActionPerformed
        // TODO add your handling code here:
        IG_Stock f = new IG_Stock();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemStockBrutAjouterActionPerformed

    private void MenuItemStockBrutSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemStockBrutSupprimerActionPerformed
        // TODO add your handling code here:
        SupprimerStockBrut f = new SupprimerStockBrut();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemStockBrutSupprimerActionPerformed

    private void MenuItemStockProduitsFinisModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemStockProduitsFinisModifierActionPerformed
        // TODO add your handling code here:
        ModifierStockProduitsFinis f = new ModifierStockProduitsFinis();
         f.setVisible(true);
    }//GEN-LAST:event_MenuItemStockProduitsFinisModifierActionPerformed

    private void MenuItemStockProduitsFinisAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemStockProduitsFinisAfficherActionPerformed
        // TODO add your handling code here:
        AffichagesDesStockProduitsFinis f = new AffichagesDesStockProduitsFinis();
         f.setVisible(true);
    }//GEN-LAST:event_MenuItemStockProduitsFinisAfficherActionPerformed

    private void MenuItemStockProduitsFinisAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemStockProduitsFinisAjouterActionPerformed
        // TODO add your handling code here:
        IG_StockProduitsFinis f = new IG_StockProduitsFinis();
         f.setVisible(true);
    }//GEN-LAST:event_MenuItemStockProduitsFinisAjouterActionPerformed

    private void MenuItemStockProduitsFinisSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemStockProduitsFinisSupprimerActionPerformed
        // TODO add your handling code here:
        SupprimerStockProduitsFinis f = new SupprimerStockProduitsFinis();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemStockProduitsFinisSupprimerActionPerformed

    private void MenuItemPlanAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPlanAfficherActionPerformed
        // TODO add your handling code here:
         MaFenetre fen = new MaFenetre();
        fen.setVisible(true);
    }//GEN-LAST:event_MenuItemPlanAfficherActionPerformed

    private void MenuItemLegendeDuPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLegendeDuPlanActionPerformed
        // TODO add your handling code here:
        MaFenetre2 f = new MaFenetre2();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemLegendeDuPlanActionPerformed

    private void MenuItemSignalerEvenementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSignalerEvenementActionPerformed
        // TODO add your handling code here:
        IG_Fiabilite f = new IG_Fiabilite();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemSignalerEvenementActionPerformed

    private void MenuItemAfficherEvenementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAfficherEvenementsActionPerformed
        // TODO add your handling code here:
        AffichageDesEvents f = new AffichageDesEvents();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemAfficherEvenementsActionPerformed

    private void MenuItemCalculerFiabiliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCalculerFiabiliteActionPerformed
        // TODO add your handling code here:
        CalculFiabilite f = new CalculFiabilite();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemCalculerFiabiliteActionPerformed

    private void MenuItemAfficherFiabilitéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAfficherFiabilitéActionPerformed
        // TODO add your handling code here:
        AffichageDesFiabilites f = new AffichageDesFiabilites();
        f.setVisible(true);
    }//GEN-LAST:event_MenuItemAfficherFiabilitéActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Atelier_Fabrication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Atelier_Fabrication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Atelier_Fabrication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Atelier_Fabrication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Atelier_Fabrication().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCompte;
    private javax.swing.JMenu MenuDeconnexion;
    private javax.swing.JMenu MenuFiabilite;
    private javax.swing.JMenu MenuGamme;
    private javax.swing.JMenuItem MenuItemAfficherEvenements;
    private javax.swing.JMenuItem MenuItemAfficherFiabilité;
    private javax.swing.JMenuItem MenuItemAfficherGamme;
    private javax.swing.JMenuItem MenuItemAfficherMachine;
    private javax.swing.JMenuItem MenuItemAfficherOperateur;
    private javax.swing.JMenuItem MenuItemAfficherOperation;
    private javax.swing.JMenuItem MenuItemAfficherPoste;
    private javax.swing.JMenuItem MenuItemAfficherProduit;
    private javax.swing.JMenuItem MenuItemCalculerFiabilite;
    private javax.swing.JMenuItem MenuItemCreerGamme;
    private javax.swing.JMenuItem MenuItemCreerMachine;
    private javax.swing.JMenuItem MenuItemCreerOperateur;
    private javax.swing.JMenuItem MenuItemCreerOperation;
    private javax.swing.JMenuItem MenuItemCreerPoste;
    private javax.swing.JMenuItem MenuItemCreerProduit;
    private javax.swing.JMenuItem MenuItemInformationsCompte;
    private javax.swing.JMenuItem MenuItemLegendeDuPlan;
    private javax.swing.JMenuItem MenuItemModifierGamme;
    private javax.swing.JMenuItem MenuItemModifierMachine;
    private javax.swing.JMenuItem MenuItemModifierOperateur;
    private javax.swing.JMenuItem MenuItemModifierOperation;
    private javax.swing.JMenuItem MenuItemModifierPoste;
    private javax.swing.JMenuItem MenuItemModifierProduit;
    private javax.swing.JMenuItem MenuItemParametresCompte;
    private javax.swing.JMenuItem MenuItemPlanAfficher;
    private javax.swing.JMenuItem MenuItemSeDeconnecterNON;
    private javax.swing.JMenuItem MenuItemSeDeconnecterOUI;
    private javax.swing.JMenuItem MenuItemSignalerEvenement;
    private javax.swing.JMenuItem MenuItemStockBrutAfficher;
    private javax.swing.JMenuItem MenuItemStockBrutAjouter;
    private javax.swing.JMenuItem MenuItemStockBrutModifier;
    private javax.swing.JMenuItem MenuItemStockBrutSupprimer;
    private javax.swing.JMenuItem MenuItemStockProduitsFinisAfficher;
    private javax.swing.JMenuItem MenuItemStockProduitsFinisAjouter;
    private javax.swing.JMenuItem MenuItemStockProduitsFinisModifier;
    private javax.swing.JMenuItem MenuItemStockProduitsFinisSupprimer;
    private javax.swing.JMenuItem MenuItemSupprimerGamme;
    private javax.swing.JMenuItem MenuItemSupprimerMachine;
    private javax.swing.JMenuItem MenuItemSupprimerOperateur;
    private javax.swing.JMenuItem MenuItemSupprimerOperation;
    private javax.swing.JMenuItem MenuItemSupprimerPoste;
    private javax.swing.JMenuItem MenuItemSupprimerProduit;
    private javax.swing.JMenu MenuMachine;
    private javax.swing.JMenu MenuOperateur;
    private javax.swing.JMenu MenuOperation;
    private javax.swing.JMenu MenuPlan;
    private javax.swing.JMenu MenuPoste;
    private javax.swing.JMenu MenuProduit;
    private javax.swing.JMenu MenuSeDeconnecter;
    private javax.swing.JMenu MenuStockBrut;
    private javax.swing.JMenu MenuStockProduitsFinis;
    private javax.swing.JMenu MenuStocks;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    // End of variables declaration//GEN-END:variables
}
